name: backups
on:
  repository_dispatch:
    types: [new_notebook_version]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: backup
        run: |
          set -euxo pipefail
          echo 'payload: ${{ toJson(github.event.client_payload) }}'
          curl 'https://api.observablehq.com/d/${{github.event.client_payload.id}}@${{github.event.client_payload.version}}.tgz?v=3' > notebook.tgz
          URL="${{github.event.client_payload.url}}"
          path="${URL/https:\/\/observablehq.com\//}"
          rm -rf "${path}"
          mkdir -p "${path}"
          tar -xf notebook.tgz -C "${path}"
          git config --global user.name 'backup-to-github'
          git config --global user.email 'robot@webcode.run'
          git add "${path}"
          git pull
          if ! git diff-index --quiet HEAD; then
            git commit -m 'Backup ${{github.event.client_payload.id}}@${{github.event.client_payload.version}}   
            ${{toJson(github.event.client_payload)}}
            '
            git push
          fi
